export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: "Apple" | "Samsung";
  model: string;
  price: number;
  oldPrice: number;
  storage: string;
  ram: string;
  batteryHealth: string;
  condition: "Excellent" | "Very Good" | "Good" | "New";
  color: string;
  warranty: string;
  availability: "In stock" | "Reserved" | "Sold" | "Out of stock";
  support5g: boolean;
  cameraQuality: "Pro" | "Flagship" | "Advanced";
  rating: number;
  reviews: number;
  sold: number;
  views: number;
  featured: boolean;
  createdAt: string;
  description: string;
  images: string[];
  specs: Record<string, string>;
};

const phoneImages = [
  "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?auto=format&fit=crop&w=1200&q=80",
];

export const products: Product[] = [
  {
    id: "p-iphone-15-pro",
    slug: "iphone-15-pro-256gb-natural-titanium",
    name: "iPhone 15 Pro",
    brand: "Apple",
    model: "15 Pro",
    price: 1280000,
    oldPrice: 1420000,
    storage: "256GB",
    ram: "8GB",
    batteryHealth: "96%",
    condition: "Excellent",
    color: "Natural Titanium",
    warranty: "6 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Pro",
    rating: 4.9,
    reviews: 58,
    sold: 41,
    views: 941,
    featured: true,
    createdAt: "2026-05-08",
    description: "A premium Pro iPhone with titanium build, powerful cameras, clean battery health, and verified Face ID.",
    images: [phoneImages[0], phoneImages[1], phoneImages[3]],
    specs: {
      Display: "6.1-inch Super Retina XDR OLED, ProMotion",
      Processor: "A17 Pro",
      Camera: "48MP main, 12MP ultra wide, 12MP telephoto",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K Dolby Vision up to 60 fps",
      "Battery capacity": "3274 mAh",
      "Charging speed": "20W wired, MagSafe wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-s24-ultra",
    slug: "samsung-galaxy-s24-ultra-512gb-titanium-black",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    model: "S24 Ultra",
    price: 1395000,
    oldPrice: 1530000,
    storage: "512GB",
    ram: "12GB",
    batteryHealth: "100%",
    condition: "New",
    color: "Titanium Black",
    warranty: "12 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Flagship",
    rating: 4.8,
    reviews: 44,
    sold: 37,
    views: 836,
    featured: true,
    createdAt: "2026-05-12",
    description: "Samsung's top flagship with S Pen, excellent display, long battery life, and a sharp 200MP camera system.",
    images: [phoneImages[2], phoneImages[5], phoneImages[4]],
    specs: {
      Display: "6.8-inch Dynamic AMOLED 2X, 120Hz",
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      Camera: "200MP wide, 50MP periscope, 10MP telephoto, 12MP ultra wide",
      "Front camera": "12MP",
      "Video recording": "8K up to 30 fps",
      "Battery capacity": "5000 mAh",
      "Charging speed": "45W wired, wireless charging",
      "Face ID/Fingerprint": "Ultrasonic fingerprint",
      "Operating system": "Android 15 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-17",
    slug: "iphone-17-256gb-mist-blue",
    name: "iPhone 17",
    brand: "Apple",
    model: "17",
    price: 1490000,
    oldPrice: 1620000,
    storage: "256GB",
    ram: "8GB",
    batteryHealth: "100%",
    condition: "New",
    color: "Mist Blue",
    warranty: "12 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Pro",
    rating: 4.9,
    reviews: 18,
    sold: 12,
    views: 524,
    featured: true,
    createdAt: "2026-05-16",
    description: "Latest iPhone series with A19 performance, a brighter 120Hz OLED display, upgraded cameras, and verified warranty support.",
    images: [phoneImages[0], phoneImages[3], phoneImages[1]],
    specs: {
      Display: "6.3-inch Super Retina XDR OLED, ProMotion",
      Processor: "A19",
      Camera: "48MP dual Fusion camera system",
      "Front camera": "18MP Center Stage camera",
      "Video recording": "4K Dolby Vision",
      "Battery capacity": "Apple-rated all-day battery, up to 30 hours video playback",
      "Charging speed": "USB-C fast charging, MagSafe wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 26 ready",
      "Water resistance": "IP68",
      "SIM type": "eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-16",
    slug: "iphone-16-256gb-ultramarine",
    name: "iPhone 16",
    brand: "Apple",
    model: "16",
    price: 1120000,
    oldPrice: 1240000,
    storage: "256GB",
    ram: "8GB",
    batteryHealth: "98%",
    condition: "Excellent",
    color: "Ultramarine",
    warranty: "6 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Pro",
    rating: 4.8,
    reviews: 36,
    sold: 28,
    views: 762,
    featured: true,
    createdAt: "2026-05-14",
    description: "Modern iPhone with A18 performance, Camera Control, Apple Intelligence support, and a clean verified body.",
    images: [phoneImages[1], phoneImages[0], phoneImages[3]],
    specs: {
      Display: "6.1-inch Super Retina XDR OLED",
      Processor: "A18",
      Camera: "48MP Fusion main, 12MP ultra wide",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K Dolby Vision",
      "Battery capacity": "Apple-rated all-day battery, up to 22 hours video playback",
      "Charging speed": "USB-C fast charging, MagSafe wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-14-pro-max",
    slug: "iphone-14-pro-max-256gb-deep-purple",
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    model: "14 Pro Max",
    price: 1050000,
    oldPrice: 1190000,
    storage: "256GB",
    ram: "6GB",
    batteryHealth: "91%",
    condition: "Very Good",
    color: "Deep Purple",
    warranty: "3 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Pro",
    rating: 4.8,
    reviews: 76,
    sold: 63,
    views: 1202,
    featured: true,
    createdAt: "2026-04-30",
    description: "Large-screen Pro iPhone with Dynamic Island, strong battery performance, and professional camera quality.",
    images: [phoneImages[1], phoneImages[0], phoneImages[3]],
    specs: {
      Display: "6.7-inch Super Retina XDR OLED, ProMotion",
      Processor: "A16 Bionic",
      Camera: "48MP main, 12MP ultra wide, 12MP telephoto",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K Dolby Vision",
      "Battery capacity": "4323 mAh",
      "Charging speed": "20W wired, MagSafe wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-12",
    slug: "iphone-12-128gb-blue",
    name: "iPhone 12",
    brand: "Apple",
    model: "12",
    price: 430000,
    oldPrice: 510000,
    storage: "128GB",
    ram: "4GB",
    batteryHealth: "88%",
    condition: "Good",
    color: "Blue",
    warranty: "3 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Advanced",
    rating: 4.5,
    reviews: 67,
    sold: 74,
    views: 1328,
    featured: false,
    createdAt: "2026-04-19",
    description: "A reliable 5G iPhone with OLED display, clean cameras, and strong value for everyday use.",
    images: [phoneImages[3], phoneImages[1], phoneImages[0]],
    specs: {
      Display: "6.1-inch Super Retina XDR OLED",
      Processor: "A14 Bionic",
      Camera: "12MP dual camera",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K Dolby Vision",
      "Battery capacity": "2815 mAh",
      "Charging speed": "20W wired, MagSafe wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-11",
    slug: "iphone-11-128gb-black",
    name: "iPhone 11",
    brand: "Apple",
    model: "11",
    price: 310000,
    oldPrice: 380000,
    storage: "128GB",
    ram: "4GB",
    batteryHealth: "86%",
    condition: "Good",
    color: "Black",
    warranty: "3 months",
    availability: "In stock",
    support5g: false,
    cameraQuality: "Advanced",
    rating: 4.4,
    reviews: 103,
    sold: 126,
    views: 1860,
    featured: false,
    createdAt: "2026-04-12",
    description: "Budget-friendly iPhone with Face ID, dual cameras, solid battery health, and dependable everyday performance.",
    images: [phoneImages[4], phoneImages[1], phoneImages[3]],
    specs: {
      Display: "6.1-inch Liquid Retina HD LCD",
      Processor: "A13 Bionic",
      Camera: "12MP dual camera",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K up to 60 fps",
      "Battery capacity": "3110 mAh",
      "Charging speed": "18W wired, Qi wireless",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE",
      "5G support": "No",
    },
  },
  {
    id: "p-s23-plus",
    slug: "samsung-galaxy-s23-plus-256gb-phantom-black",
    name: "Samsung Galaxy S23+",
    brand: "Samsung",
    model: "S23+",
    price: 790000,
    oldPrice: 880000,
    storage: "256GB",
    ram: "8GB",
    batteryHealth: "97%",
    condition: "Excellent",
    color: "Phantom Black",
    warranty: "6 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Advanced",
    rating: 4.7,
    reviews: 39,
    sold: 31,
    views: 622,
    featured: true,
    createdAt: "2026-05-04",
    description: "Fast Galaxy flagship with excellent display, reliable cameras, and generous storage for everyday power users.",
    images: [phoneImages[5], phoneImages[2], phoneImages[4]],
    specs: {
      Display: "6.6-inch Dynamic AMOLED 2X, 120Hz",
      Processor: "Snapdragon 8 Gen 2",
      Camera: "50MP main, 10MP telephoto, 12MP ultra wide",
      "Front camera": "12MP",
      "Video recording": "8K up to 30 fps",
      "Battery capacity": "4700 mAh",
      "Charging speed": "45W wired",
      "Face ID/Fingerprint": "Fingerprint",
      "Operating system": "Android 15 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-iphone-13",
    slug: "iphone-13-128gb-midnight",
    name: "iPhone 13",
    brand: "Apple",
    model: "13",
    price: 530000,
    oldPrice: 610000,
    storage: "128GB",
    ram: "4GB",
    batteryHealth: "89%",
    condition: "Good",
    color: "Midnight",
    warranty: "3 months",
    availability: "Reserved",
    support5g: true,
    cameraQuality: "Advanced",
    rating: 4.6,
    reviews: 91,
    sold: 88,
    views: 1514,
    featured: false,
    createdAt: "2026-04-17",
    description: "A clean daily iPhone with 5G, dependable camera quality, and strong value for students and professionals.",
    images: [phoneImages[3], phoneImages[1], phoneImages[0]],
    specs: {
      Display: "6.1-inch Super Retina XDR OLED",
      Processor: "A15 Bionic",
      Camera: "12MP dual camera",
      "Front camera": "12MP TrueDepth",
      "Video recording": "4K Dolby Vision",
      "Battery capacity": "3240 mAh",
      "Charging speed": "20W wired",
      "Face ID/Fingerprint": "Face ID",
      "Operating system": "iOS 18 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM + eSIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
  {
    id: "p-s21-fe",
    slug: "samsung-galaxy-s21-fe-128gb-olive",
    name: "Samsung Galaxy S21 FE",
    brand: "Samsung",
    model: "S21 FE",
    price: 390000,
    oldPrice: 460000,
    storage: "128GB",
    ram: "6GB",
    batteryHealth: "92%",
    condition: "Very Good",
    color: "Olive",
    warranty: "3 months",
    availability: "In stock",
    support5g: true,
    cameraQuality: "Advanced",
    rating: 4.5,
    reviews: 33,
    sold: 52,
    views: 704,
    featured: false,
    createdAt: "2026-04-24",
    description: "A slim 5G Galaxy with a bright AMOLED screen, solid cameras, and a friendly price.",
    images: [phoneImages[4], phoneImages[5], phoneImages[2]],
    specs: {
      Display: "6.4-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 888",
      Camera: "12MP main, 8MP telephoto, 12MP ultra wide",
      "Front camera": "32MP",
      "Video recording": "4K up to 60 fps",
      "Battery capacity": "4500 mAh",
      "Charging speed": "25W wired",
      "Face ID/Fingerprint": "Fingerprint",
      "Operating system": "Android 14 ready",
      "Water resistance": "IP68",
      "SIM type": "Nano SIM",
      "Network support": "4G LTE / 5G",
      "5G support": "Yes",
    },
  },
];

export const reviews = [
  {
    name: "Aline Uwase",
    rating: 5,
    photo: "https://images.unsplash.com/photo-1631346543932-ce110c10dbec?auto=format&fit=crop&w=240&q=80",
    text: "I compared three iPhones before buying. The battery health was exactly as listed and delivery in Kigali was fast.",
  },
  {
    name: "Kevin Mugisha",
    rating: 5,
    photo: "https://images.unsplash.com/photo-1769636929354-59165ba73c7e?auto=format&fit=crop&w=240&q=80",
    text: "The team helped me choose between Samsung and iPhone without pressure. Very clean phone and clear warranty.",
  },
  {
    name: "Diane Ishimwe",
    rating: 5,
    photo: "https://images.unsplash.com/photo-1641522682664-5829139c4e80?auto=format&fit=crop&w=240&q=80",
    text: "The WhatsApp ordering process felt professional. I reserved my phone, checked it, and paid after confirmation.",
  },
];

export function findProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
